### ISSUE TITLE
data types architecture (sponsored: due feb 1)

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#166]
placeholder issue for 1st class data type support in dash-table

Phase I - Type support
- [x] #280 (prep work)
- [x] #297 (first pass at data type support -- for existing types)
- [x] [Datetime type](https://github.com/plotly/dash-table/pull/364)
- [x] #342 (support conditionals based on column type)
- [ ] type inference with filtering
- [ ] type inference / precedence with sorting
- [ ] #332 (make numeric columns return number when possible instead of string)
- [ ] update dash docs
- [ ] clearly document the upgrade path (3.1 --> 3.2)

Phase II+
Related issues:
- [x] #189 type=number formatting
- #232 
- #248
- #305 (number styling)
- #331 (date picker)

**Comment by chriddyp** [comment]
There is a lot to consider here. I've started considering 'what data types means in the table' in this gist, https://gist.github.com/chriddyp/afcaf01d124b610e69de066753d36fc5, and I'll update this thread as I make more progress spec'ing this out.

**Comment by chriddyp** [comment]
Great first pass on data types 🚀 . We can create separate issues for more features as they come up.
